# 2.3 Lab: Introduction to ~~R~~ Python

## 2.3.3 Indexing Data

In this lab, we will work through subsetting data. 

### Imports


In [1]:
from typing import List, Dict, Tuple, Sequence, Union # annotation library
import sys # system library 

import statsmodels # root namespace for intellisense and deep reference
import statsmodels.api as statsModels # alias to hide the extra api namespace

import numpy   # as np
import pandas  # as pd

from sklearn import * # import all child namespaces 

import matplotlib.pyplot as pyplot
from mpl_toolkits import mplot3d   # matplotlib 3d plotting
import seaborn 

### Indexing 

It is important to note that R starts indexing from 1 while Python starts indexing from 0. You will need to reduce the index by 1 to match Python to R. 

**R Code**
```R
A = matrix (1:16, 4, 4)
A
     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16

# 2nd row, 3rd column
A [2, 3]
 [1] 10
```

In [2]:
A = numpy.arange (1, 17).reshape (4, 4, order = "F")
print (A)

print ("\nelement at R [2, 3] and Python [1, 2]")
print (A [1, 2])

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

element at R [2, 3] and Python [1, 2]
10


### Slicing 

Slicing is taken a subset of rows and/or columns. The arrays generated by basic slicing are always views of the original array and not new copied. A view is an array that doesn't own its own data but contains references back to the original array. 

When slicing in Python using `start:end`, the interval is `[start, end)` where end is not included in the result.

**R Code** 
```R
A [c (1, 3), c (2, 4)]
     [,1] [,2]
[1,]    5   13
[2,]    7   15

A [1:3, 2:4]
     [,1] [,2] [,3]
[1,]    5    9   13
[2,]    6   10   14
[3,]    7   11   15

A [1:2, ]
     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14

A [, 1:2]
     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8

A [1,  ]
[1]  1  5  9 13

A [-c (1, 3), ]
     [,1] [,2] [,3] [,4]
[1,]    2    6   10   14
[2,]    4    8   12   16

dim (A)
[1] 4 4 
```

In [3]:
# A [c (1, 3), c (2, 4)], reduce by 1 for Python 
A [(0,2), :][:, (1, 3)]

array([[ 5, 13],
       [ 7, 15]])

In [4]:
# A [1:3, 2:4], reduce by 1 for Python and increasing the end by 1
A [0:3, 1:4]

array([[ 5,  9, 13],
       [ 6, 10, 14],
       [ 7, 11, 15]])

In [5]:
# A [1:2, ],reduce by 1 and increasing the end by 1
A [0:2, :]

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14]])

In [6]:
# A [, 1:2], reduce by 1 and increasing the end by 1
A [:, 0:2]

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [7]:
# A[1, ], reduce by 1 
A [0, :]

array([ 1,  5,  9, 13])

In [8]:
# A [-c (1, 3), ], reduce by 1
# delete returns a new array with the rows removed by index 
numpy.delete (A, [0, 2], axis = 0)

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])

In [9]:
# dim (A)
A.shape 

(4, 4)